### PR TITLE
Converted to ES6 syntax

### PR DESCRIPTION
**Pull request by cerberusv2px**

### CODE REVIEW

**Comment by mesaugat** [comment]
@cerberusv2px Thank you for the pull request. But hey the tests are not passing right now. Are you sure this works?

If it does, can you make the tests pass?

```
/home/travis/build/mesaugat/express-api-es6-starter/src/knexfile.js:1
(function (exports, require, module, __filename, __dirname) { import 'babel-register';
                                                                     ^^^^^^^^^^^^^^^^
```

Take a look here: https://travis-ci.org/mesaugat/express-api-es6-starter/jobs/421923636

**Comment by cerberusv2px** [comment]
Looks like some of the ES6 syntax is still not supported in NodeJS

**Comment by mesaugat** [comment]
@cerberusv2px Yes `import` is not supported and hidden behind an experimental flag. What should work is this:

```diff
- import 'babel-register';
+ require('babel-register');
```

Rest of the syntax can be ES6.

You can try this out and send in a pull request.

**Comment by cerberusv2px** [comment]
I tried that it shows syntax error in the rest of the code below. I tried something like this:

```export const client = process.env.DB_CLIENT;```

**Comment by mesaugat** [comment]
@cerberusv2px If you want to do it, it looks possible with `babel-node`. https://github.com/tgriesser/knex/issues/1232#issuecomment-271999072

`module.exports` doesn't seem that bad in my opinion.

**Comment by cerberusv2px** [comment]
Ok thanks. I will have a look at it.

**Pull request closed without merging**
